version: "3.7"

services:
  api:
    build:
      context: ./bot-api
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - ./bot-api/.env
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - MYSQL_HOST_PROD=${MYSQL_HOST_PROD}
      - MYSQL_PORT_PROD=${MYSQL_PORT_PROD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE_PROD=${MYSQL_DATABASE_PROD}
      - PORT=${PORT}
      - ADDRESS_PROD=${ADDRESS_PROD}
    restart: always

  frontend:
    build:
      context: ./bot-front
      dockerfile: Dockerfile
    depends_on:
      - api
    restart: always
    ports:
      - "8090:80"
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro

  db:
    image: mariadb:latest
    environment:
      - MYSQL_DATABASE_PROD=${MYSQL_DATABASE_PROD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql:rw
      - ./bot-api/schema/init.sql:/docker-entrypoint-initdb.d/init.sql:ro