version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      .env
    restart: always

  db:
    image: mariadb:latest
    env_file:
      .env
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql:rw
      - ./schema/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

# volumes:
#   mysql-datavolume: